baseURL = 'https://pinguimcriativo.com/'
languageCode = 'en-us'
title = 'O Pinguim Criativo'

[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    [params.author]
        name        = "O Pinguim Criativo"
        email       = "contato@pinguimcriativo.com"
        description = "O Pinguim Criativo - Customizações Linux Sem Limites"

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "dartsass"
        [params.galleriesdeluxe.sassvars]
            color_background = "#1d1e2c"

[params.gallerydeluxe]
    shuffle     = false
    reverse     = true
    enable_exif = false

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"
