[build.environment]
HUGO_VERSION = "0.124.0"
DART_SASS_VERSION = "1.71.0"
TZ = "America/Sao_Paulo"

[build]
publish = "public"
command = """
  curl -LJO https://github.com/sass/dart-sass/releases/download/1.71.0/dart-sass-1.71.0-linux-x64.tar.gz && \
  tar -xf dart-sass-1.71.0-linux-x64.tar.gz && \
  rm dart-sass-1.71.0-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify
"""
